server:
  port: 8085
  servlet:
    context-path: /api/account
management:
  server:
    port: 8185
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: account
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  application:
    name: account-app
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
      reload:
        enabled: true
  kafka:
    bootstrap-servers: 192.168.1.115:9092
    partitions: 3
    replicas: 1
    consumer:
      auto-offset-reset: earliest
      group-id: account-app-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
