apiVersion: v1
kind: ConfigMap
metadata:
  name: account-app-config
  namespace: default
data:
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  kafka-bootstrap-servers: "192.168.1.115:9092"
  datasource-url: "jdbc:postgresql://192.168.1.115:5433/postgres?currentSchema=account"
  datasource-username: "postgres"
  kafka.topics.account-create: "account.create"
  kafka.topics.account-update: "account.update"
  kafka.topics.account-delete: "account.delete"
  kafka.topics.account-get: "account.get"
  kafka.topics.account-get-by-id: "account.getById"
  kafka.topics.error-logs: "error.logs"
  kafka.topics.audit-logs: "audit.logs"
  kafka.topics.external-account-create: "external.account.create"
  kafka.topics.external-account-update: "external.account.update"
  kafka.topics.external-account-delete: "external.account.delete"
  kafka.topics.external-account-get: "external.account.get"
  kafka.topics.external-account-get-by-id: "external.account.getById"
  kafka.topics.external-audit-logs: "external.audit.logs"
  kafka.topics.auth-validate: "auth.validate"
  kafka.topics.auth-validate-response: "auth.validate.response"
  kafka.header: "Authorization"
  audit.default-user: "SYSTEM"
  audit.entity-type: "ACCOUNT"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "account-app-group"
  kafka.groups.account: "account-group"
  kafka.groups.audit: "audit-group"

