apiVersion: v1
kind: Service
metadata:
  name: authorization-service
spec:
  selector:
    app: authorization-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-app-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "DEBUG"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service-1:9092"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://bank-db:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: authorization-app-secret
  namespace: default
type: Opaque
data:
   SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-app
  template:
    metadata:
      labels:
        app: authorization-app
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka-service-1 9092; do echo waiting for Kafka; sleep 2; done;']
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z bank-db 5432; do echo waiting for PostgreSQL; sleep 2; done;']
      containers:
        - name: authorization-app
          image: authorization-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: authorization-app-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "1500m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: authorization-app-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: authorization-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: authorization-app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authorization-app-secret
                  key: SPRING_DATASOURCE_PASSWORD
