apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bank-db
  name: bank-db
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: bank-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bank-db
  name: bank-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bank-db
  template:
    metadata:
      labels:
        io.kompose.service: bank-db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: bank-db
          ports:
            - containerPort: 5432
              protocol: TCP
      hostname: bank-db
      restartPolicy: Always
