# application-local.yaml
server:
  port: 8091
  servlet:
    context-path: /
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public_info
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: public-info-app
  kafka:
    trusted-packages: com.bank.publicinfo.dto
    bootstrap-servers: host.docker.internal:9092
#    bootstrap-servers: host.docker.internal:9092  # с локального хоста
    topics:
      error-log:
        name: public-info.error-logs
        partitions: 1
        replication-factor: 1
      license:
        create:
          name: public-info.license.create
          partitions: 1
          replication-factor: 1
        update:
          name: public-info.license.update
          partitions: 1
          replication-factor: 1
        delete:
          name: public-info.license.delete
          partitions: 1
          replication-factor: 1
        get:
          name: public-info.license.get
          partitions: 1
          replication-factor: 1
      certificate:
        create:
          name: public-info.certificate.create
          partitions: 1
          replication-factor: 1
        update:
          name: public-info.certificate.update
          partitions: 1
          replication-factor: 1
        delete:
          name: public-info.certificate.delete
          partitions: 1
          replication-factor: 1
        get:
          name: public-info.certificate.get
          partitions: 1
          replication-factor: 1
      bank:
        create:
          name: public-info.bank.create
          partitions: 1
          replication-factor: 1
        update:
          name: public-info.bank.update
          partitions: 1
          replication-factor: 1
        delete:
          name: public-info.bank.delete
          partitions: 1
          replication-factor: 1
        get:
          name: public-info.bank.get
          partitions: 1
          replication-factor: 1
      branch:
        create:
          name: public-info.branch.create
          partitions: 1
          replication-factor: 1
        update:
          name: public-info.branch.update
          partitions: 1
          replication-factor: 1
        delete:
          name: public-info.branch.delete
          partitions: 1
          replication-factor: 1
        get:
          name: public-info.branch.get
          partitions: 1
          replication-factor: 1
      atm:
        create:
          name: public-info.atm.create
          partitions: 1
          replication-factor: 1
        update:
          name: public-info.atm.update
          partitions: 1
          replication-factor: 1
        delete:
          name: public-info.atm.delete
          partitions: 1
          replication-factor: 1
        get:
          name: public-info.atm.get
          partitions: 1
          replication-factor: 1


    consumer:
      group-id: public-info-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      security:
        protocol: PLAINTEXT

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui.html  # Изменить URL, если нужно
    tags-sorter: alpha               # Сортировка тегов по алфавиту
    operations-sorter: alpha         # Сортировка операций
  api-docs:
    path: /api-docs                  # Путь к JSON-документации
  show-actuator: true                # Показывать эндпоинты Actuator


  #    http://localhost:8091/api-docs/swagger-ui.html