apiVersion: v1
kind: ConfigMap
metadata:
  name: public-info-app-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "local"
  kafka-bootstrap-servers: "192.168.31.54:9092"
  datasource-url: "jdbc:postgresql://192.168.31.54:5433/postgres"
  datasource-username: "postgres"