# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-info-app-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "local"
  datasource-url: "jdbc:postgresql://host.docker.internal:5432/postgres"
  datasource-username: "postgres"
#  SPRING_DATASOURCE_PASSWORD: "password"
  kafka-bootstrap-servers: "host.docker.internal:9092"