apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-info-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-info-app
  template:
    metadata:
      labels:
        app: public-info-app
    spec:
      containers:
        - name: public-info-app
          image: doxa80/public-info-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: public-info-app-config
                  key: kafka-bootstrap-servers
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: public-info-app-config
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: public-info-app-config
                  key: datasource-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: public-info-app-secret
                  key: datasource-password

---

# Настройка Horizontal Pod Autoscaler (HPA) для автоматического масштабирования
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: public-info-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: public-info-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70