apiVersion: v1
kind: ConfigMap
metadata:
  name: antifraud-app-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "192.168.1.3:9092"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.1.115:5433/postgres?currentSchema=anti_fraud"
  SPRING_DATASOURCE_USERNAME: "postgres"
