apiVersion: apps/v1
kind: Deployment
metadata:
  name: antifraud-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: antifraudK8s-app
  template:
    metadata:
      labels:
        app: antifraudK8s-app
    spec:
      containers:
        - name: antifraud-app
          image: lucassanoss/antifraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: antifraud-app-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: antifraud-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: antifraud-app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: antifraud-secret
                  key: SPRING_DATASOURCE_PASSWORD

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: antifraud-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: antifraud-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
